import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Trash2 } from "lucide-react";
import { api } from "@/services/api";
import type { Cart as CartType } from "@/services/types";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/storefront/StoreUi";
import { money } from "@/components/storefront/ProductCard";
import { toast } from "sonner";

export default function Cart(){const cart=useQuery({queryKey:["cart"],queryFn:()=>api.get<CartType>("/cart")}); const update=async(productId:string,quantity:number)=>{await api.patch("/cart/update",{productId,quantity}); cart.refetch();}; const remove=async(productId:string)=>{await api.patch("/cart/remove",{productId}); toast("Removed from cart"); cart.refetch();}; const clear=async()=>{await api.del("/cart"); cart.refetch();}; const c=cart.data; if(!c?.items?.length) return <div className="section-shell py-16"><EmptyState title="Your cart is empty" text="Add glow essentials and come back to checkout." action={<Button asChild variant="hero"><Link to="/shop">Continue Shopping</Link></Button>}/></div>;
return <div className="section-shell py-10"><h1 className="mb-8 text-5xl font-bold text-secondary">Shopping Cart</h1><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-4">{c.items.map(i=><div key={i.product._id} className="grid grid-cols-[80px_1fr] gap-4 rounded-2xl glass-panel p-4 md:grid-cols-[96px_1fr_auto]"><img src={i.product.cover||"/placeholder.svg"} alt={i.product.name} className="h-24 w-24 rounded-xl object-cover"/><div><h3 className="font-bold text-secondary">{i.product.name}</h3><p className="text-muted-foreground">{money(i.price)} each</p><div className="mt-3 flex items-center gap-2"><Button variant="glass" size="sm" onClick={()=>update(i.product._id,Math.max(1,i.quantity-1))}>-</Button><span>{i.quantity}</span><Button variant="glass" size="sm" onClick={()=>update(i.product._id,i.quantity+1)}>+</Button></div></div><div className="flex items-center gap-3"><strong>{money(i.price*i.quantity)}</strong><Button variant="ghost" size="icon" onClick={()=>remove(i.product._id)}><Trash2/></Button></div></div>)}</div><aside className="h-fit rounded-2xl glass-panel p-6"><h2 className="mb-4 text-2xl font-bold text-secondary">Order Summary</h2><div className="space-y-3 text-sm"><p className="flex justify-between"><span>Subtotal</span><b>{money(c.totelPrice)}</b></p><p className="flex justify-between"><span>Tax</span><b>{money(c.taxPrice||c.totelPrice*0.07)}</b></p>{c.totelPriceAfterDiscount&&<p className="flex justify-between"><span>Discounted total</span><b>{money(c.totelPriceAfterDiscount)}</b></p>}<p className="flex justify-between border-t border-border pt-3 text-lg"><span>Total</span><b>{money(c.totelPriceAfterDiscount||((c.totelPrice||0)+(c.taxPrice||0)))}</b></p></div><Button asChild variant="hero" className="mt-6 w-full"><Link to="/checkout">Proceed to Checkout</Link></Button><Button variant="glass" className="mt-3 w-full" onClick={clear}>Clear Cart</Button></aside></div></div>}
