import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { SlidersHorizontal } from "lucide-react";
import { api } from "@/services/api";
import type { ApiList, Category, Product } from "@/services/types";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/storefront/ProductCard";
import { ProductSkeletonGrid, QuickView, SectionTitle } from "@/components/storefront/StoreUi";

import { useTranslation } from "@/locales/TranslationContext";

export default function Shop() { const { t, isAr }=useTranslation(); const [params,setParams]=useSearchParams(); const [quick,setQuick]=useState<Product|null>(null); const [max,setMax]=useState(50000); const [rating,setRating]=useState(0); const sort=params.get("sort")||"-createdAt"; const search=params.get("search")||""; const category=params.get("category")||""; const subcategory=params.get("subcategory")||""; const products=useQuery({queryKey:["products",sort,search,category,subcategory],queryFn:()=>api.get<ApiList<Product>>(`/products?sort=${sort}&search=${encodeURIComponent(search)}&page=1&limit=100`)}); const categories=useQuery({queryKey:["categories"],queryFn:()=>api.get<ApiList<Category>>("/categories")}); const filtered=useMemo(()=>{return (products.data?.data||[]).filter(p=>{const cid=typeof p.category==="string"?p.category:p.category?._id; const sid=typeof p.subcategory==="string"?p.subcategory:p.subcategory?._id; return (!category||cid===category) && (!subcategory||sid===subcategory) && ((p.priceAfterDiscount||p.price||0)<=max) && ((p.rateAvg||0)>=rating);});},[products.data,category,subcategory,max,rating]);
return <div className="section-shell py-10"><SectionTitle eyebrow={t.nav.shop} title={t.shop.title}><div className="flex gap-2"><select className="rounded-xl border border-input bg-background px-3 py-2" value={sort} onChange={e=>setParams({sort:e.target.value, search, category, subcategory})}><option value="-createdAt">{t.shop.sort.newest}</option><option value="-sold">{t.shop.sort.sold}</option><option value="-rateAvg">{t.shop.sort.rate}</option><option value="-price">{t.shop.sort.price_desc}</option></select></div></SectionTitle><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="h-fit rounded-2xl glass-panel p-5"><h3 className="mb-4 flex items-center gap-2 font-bold text-secondary"><SlidersHorizontal/>{t.shop.filters}</h3><label className="text-sm font-semibold">{t.shop.category}</label><select className="mt-2 w-full rounded-xl border border-input bg-background p-3" value={category} onChange={e=>setParams({sort, search, category:e.target.value, subcategory})}><option value="">{t.common.all}</option>{categories.data?.data?.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select><label className="mt-5 block text-sm font-semibold">{t.shop.max_price}: ${max}</label><input className="mt-2 w-full accent-secondary" type="range" min="10" max="50000" value={max} onChange={e=>setMax(Number(e.target.value))}/><label className="mt-5 block text-sm font-semibold">{t.shop.min_rating}</label><select className="mt-2 w-full rounded-xl border border-input bg-background p-3" value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="0">{t.shop.any}</option><option value="4">{t.shop.stars_4}</option><option value="3">{t.shop.stars_3}</option></select></aside><div>{products.isLoading?<ProductSkeletonGrid count={12}/>:filtered.length === 0 ? <div className="text-center py-20 text-muted-foreground">{isAr ? "لا توجد منتجات مطابقة." : "No matching products found."}</div> : <div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{filtered.map(p=><ProductCard key={p._id} product={p} onQuickView={setQuick}/>)}</div>}<div className="mt-8 flex justify-center gap-2"><Button variant="glass" disabled>{t.common.prev}</Button><Button variant="glass">{t.common.page} 1</Button><Button variant="glass" disabled>{t.common.next}</Button></div></div></div><QuickView product={quick} open={!!quick} onOpenChange={(o)=>!o&&setQuick(null)}/></div> }

