import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { SlidersHorizontal } from "lucide-react";
import { api } from "@/services/api";
import type { ApiList, Category, Product } from "@/services/types";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/storefront/ProductCard";
import { ProductSkeletonGrid, QuickView, SectionTitle } from "@/components/storefront/StoreUi";

export default function Shop() { const [params,setParams]=useSearchParams(); const [quick,setQuick]=useState<Product|null>(null); const [max,setMax]=useState(500); const [rating,setRating]=useState(0); const sort=params.get("sort")||"-createdAt"; const search=params.get("search")||""; const category=params.get("category")||""; const products=useQuery({queryKey:["products",sort,search],queryFn:()=>api.get<ApiList<Product>>(`/products?sort=${sort}&search=${encodeURIComponent(search)}&page=1&limit=100`)}); const categories=useQuery({queryKey:["categories"],queryFn:()=>api.get<ApiList<Category>>("/categories")}); const filtered=useMemo(()=>{return (products.data?.data||[]).filter(p=>{const cid=typeof p.category==="string"?p.category:p.category?._id; return (!category||cid===category) && (p.priceAfterDiscount||p.price)<=max && (p.rateAvg||0)>=rating;});},[products.data,category,max,rating]);
return <div className="section-shell py-10"><SectionTitle eyebrow="Shop" title="All Beauty Essentials"><div className="flex gap-2"><select className="rounded-xl border border-input bg-background px-3 py-2" value={sort} onChange={e=>setParams({sort:e.target.value, search, category})}><option value="-createdAt">Newest</option><option value="-sold">Best sellers</option><option value="-rateAvg">Top rated</option><option value="-price">Price high</option></select></div></SectionTitle><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="h-fit rounded-2xl glass-panel p-5"><h3 className="mb-4 flex items-center gap-2 font-bold text-secondary"><SlidersHorizontal/>Filters</h3><label className="text-sm font-semibold">Category</label><select className="mt-2 w-full rounded-xl border border-input bg-background p-3" value={category} onChange={e=>setParams({sort, search, category:e.target.value})}><option value="">All</option>{categories.data?.data?.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select><label className="mt-5 block text-sm font-semibold">Max price: ${max}</label><input className="mt-2 w-full accent-secondary" type="range" min="10" max="1000" value={max} onChange={e=>setMax(Number(e.target.value))}/><label className="mt-5 block text-sm font-semibold">Rating</label><select className="mt-2 w-full rounded-xl border border-input bg-background p-3" value={rating} onChange={e=>setRating(Number(e.target.value))}><option value="0">Any</option><option value="4">4+ stars</option><option value="3">3+ stars</option></select></aside><div>{products.isLoading?<ProductSkeletonGrid count={12}/>:<div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{filtered.map(p=><ProductCard key={p._id} product={p} onQuickView={setQuick}/>)}</div>}<div className="mt-8 flex justify-center gap-2"><Button variant="glass" disabled>Prev</Button><Button variant="glass">Page 1</Button><Button variant="glass" disabled>Next</Button></div></div></div><QuickView product={quick} open={!!quick} onOpenChange={(o)=>!o&&setQuick(null)}/></div> }
