import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Product } from "@/services/types";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { money, Stars } from "./ProductCard";
import { useTranslation } from "@/locales/TranslationContext";
import {Link} from "react-router-dom";

export function SectionTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: React.ReactNode }) { return <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-2 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-secondary"><Sparkles className="h-4 w-4" />{eyebrow}</p>}<h2 className="text-3xl font-bold text-secondary md:text-5xl">{title}</h2></div>{children}</div>; }
export function ProductSkeletonGrid({ count = 8 }: { count?: number }) { return <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({length:count}).map((_,i)=><div key={i} className="overflow-hidden rounded-2xl glass-panel"><div className="aspect-[4/5] shimmer"/><div className="space-y-3 p-4"><div className="h-4 rounded shimmer"/><div className="h-3 w-2/3 rounded shimmer"/><div className="h-8 rounded shimmer"/></div></div>)}</div>; }
export function EmptyState({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="mx-auto max-w-md rounded-3xl glass-panel p-8 text-center"><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-full bg-blush shadow-glow"><Sparkles className="h-9 w-9 text-secondary" /></div><h3 className="text-2xl font-bold text-secondary">{title}</h3><p className="mt-2 text-muted-foreground">{text}</p><div className="mt-6">{action}</div></div>; }
export function QuickView({ product, open, onOpenChange }: { product?: Product | null; open: boolean; onOpenChange: (open: boolean) => void }) { const { t, isAr }=useTranslation(); if (!product) return null; const sale = product.priceAfterDiscount && product.priceAfterDiscount < product.price; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-3xl rounded-3xl glass-panel"><DialogHeader><DialogTitle className="text-3xl text-secondary">{product.name}</DialogTitle></DialogHeader><div className="grid gap-6 md:grid-cols-2"><img src={product.cover || product.images?.[0] || "/placeholder.svg"} alt={product.name} className="aspect-square rounded-2xl object-cover"/><div className="space-y-4"><Stars value={product.rateAvg} count={product.rating}/><p className="text-muted-foreground line-clamp-5">{product.description || (isAr ? "أساسي تجميل منتقى لطقوسك اليومية." : "A luminous beauty essential selected for your everyday ritual.")}</p><div className="flex items-baseline gap-3"><span className="text-2xl font-bold text-secondary">{money(product.priceAfterDiscount || product.price)}</span>{sale && <span className="line-through text-muted-foreground">{money(product.price)}</span>}</div><Button asChild variant="hero"><Link to={`/products/${product._id}`}>{isAr ? "عرض التفاصيل" : "View details"}</Link></Button></div></div></DialogContent></Dialog>; }
